In [3]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [7]:
from scipy import sparse

#Create a 2D NumPy array with a diag of ones, and zeros everywhere else
eye = np.eye(4)
print("Numpy array:\n{}".format(eye))

Numpy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Convert the NumPy array to a SciPy sparce matrix in CSR format
# Only the nonzero entries are stored

sparse_matrix = sparse.csr_matrix(eye)
print("\n SciPy sparse CSR matris:\n{}".format(sparse_matrix))


 SciPy sparse CSR matris:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
